### ISSUE TITLE
Persistent Volumes

### ISSUE THREAD

**Issue by josephglanville** [flynn/flynn#2438]
This is a preliminary list of the work required to get persistent volumes working in a best-effort fashion.
That is if the volume is available it will be used again, else a job will be scheduled with a new volume.
Additional deployer and scheduler strategies/policies are out of the scope of this initial work.
- [x] Add volumes_cache table to schema
- [x] Add volumes API to controller
- [x] Teach scheduler to sync volumes with controller
- [x] Enhance the scheduler to use previous volume information to schedule jobs to re-use volumes.
- [x] Add volumes CLI to display volumes and their attachments

**Comment by josephglanville** [comment]
Work is happening on this branch https://github.com/flynn/flynn/tree/persistent-volumes

**Comment by holtgrewe** [comment]
Would this also add support for large volumes where data is only read after writing them once? I am planning to deploy some Bioinformatics tools with Flynn. Such programs often use large "database" files that are used for answering user queries.

Adjusting the programs to just put everything into a postgres database is usually not easy but no update is required to the database files after a volume is created.

**Comment by titanous** [comment]
@holtgrewe I think our work on squashfs images in #3100 is relevant, it would allow you to put a dataset in a compressed squashfs file that is part of the container image definition.

**Comment by lmars** [comment]
@josephglanville I was taking a look through the changes on the persistent-volumes branch to see what scheduler changes are needed, and although you mention additional deploy strategies are out of scope, I do think we need to take deployments into consideration.

This is my understanding of the current proposed approach when starting a job which requires a volume:

* if no volumes exist for the given app + process type, create a new one
* if volumes exist for the given app + process type but they are all attached, create a new one
* if volumes exist for the given app + process type and one is unattached, use it

This works well to maintain volume attachments when jobs restart (which is useful for db appliances when a host is rebooted for example), but then it leads to the following scenario during deployments:

* `one-by-one`: the first new job gets a new volume, then subsequent new jobs get the volume from the previously stopped job, then leaving a single unattached volume when the last job stops
* `all-at-once`: all new jobs come up with new volumes, old jobs stop leaving N unattached volumes

We now have a pool of unattached volumes which get stale over time, and then the next deployment will use these stale volumes.

This is probably ok for jobs which manage their own replication (they will just bring the stale data up-to-date), but for non replicated appliances like Redis where we just want a single job with the same data, the first deployment would effectively lose the data, and then subsequent deploys would rollback the data to when the last deploy happened.

So, I propose:

* rename `one-by-one` -> `one-up-one-down`, `all-at-once` to `all-up-all-down`, always use new volumes for each release (thus expecting the jobs to perform their own replication, like postgres / mariadb / mongodb)
* add `one-down-one-up`, `all-down-all-up`, re-use volumes across releases (so redis for example would maintain its data through a deployment, but would incur some downtime)
* always re-use volumes when jobs restart

To achieve this, I think we should add an optional `Volume.ReleaseID` which when set means that volume can only be attached to jobs from the same release (so set for `one-up-one-down` / `all-up-all-down` but unset for `one-down-one-up` / `all-down-all-up`).

Thoughts?

**Comment by josephglanville** [comment]
Agreed on all points, we have discussed most of this before but it's good to have it written up canonically.

**Comment by jroitgrund** [comment]
I have a related question - didn't want to open a new issue. In release that don't support persistent volumes, does a provisioned Postgres lose all its data on system reboot?

**Comment by titanous** [comment]
@jroitgrund No, flynn-host reattaches the volumes at start.

**Comment by aaomidi** [comment]
Is this ready to be used yet? :)

**Comment by apauly** [comment]
Is there still any activity on this feature?

**Comment by titanous** [comment]
This was implemented in #3897.

**Comment by philiplb** [comment]
Including the possibility to backup and restore the volume of an app?

**Comment by titanous** [comment]
No, this issue was about an optimization for the Flynn data appliances, for backup/restore you'd use the app resource and cluster-level backup/restore functionality.

**Comment by philiplb** [comment]
Thanks.
So if I add a volume to the app, write files to it during the apps runtime, the volume will be included within the cluster backup and restore? That would be brillant.

**Comment by titanous** [comment]
> So if I add a volume to the app, write files to it during the apps runtime, the volume will be included within the cluster backup and restore?

No, volumes themselves are not backed up, as there are usually several (one per host per datastore) with the same data that is tied to the datastore version. We take a logical backup from the datastores that can be restored to a newer version.

**Comment by philiplb** [comment]
Ok, I can't run older apps using the filesystem for fileuploads or a SQLite on Flynn, yet. :)
Thank you for the answer.
