### ISSUE TITLE
MVP TODO

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#7]
### Layer 0
- [x] Scheduling framework ([sampi](https://github.com/flynn/sampi))
- [x] Host service ([lorne](https://github.com/flynn/lorne))
- [x] Service discovery ([discover](https://github.com/flynn/go-discover))
### Layer 1
- [x] CLI tool
- [x] Management API
- [x] Git receive server ([gitreceive-next](https://github.com/flynn/gitreceive-next))
- [x] Buildpack runner ([slugbuilder](https://github.com/flynn/slugbuilder))
- [x] TCP/HTTP router ([strowger](https://github.com/flynn/strowger))
