### ISSUE TITLE
Controller refactor

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#744]
- [x] Move from martini to httprouter (use [Context](https://godoc.org/golang.org/x/net/context) to pass around request-scoped data)
- [x] Validate requests using JSON schemas (#471)
- [x] Full input validation (#528)
- [ ] List pagination (#533)
- [x] Standardize error returns (status code + body) (discussed in #322)

**Comment by titanous** [comment]
@lmars @archSeer If you have any suggestions about things that could be improved in the controller, please propose them here.

**Comment by archSeer** [comment]
I think it'd be good if we got to use concrete types on repos (for instance `AppRepo.Add`), as that would do away with a lot of type casts. I don't know if it's possible though, due to the way the CRUD mapper works.

**Comment by titanous** [comment]
I might be possible to use reflection with the CRUD mapper, I can take a look.

**Comment by archSeer** [comment]
It's already using reflection in most of the calls, the real problem is going around the the interface validation we do [here](https://github.com/flynn/flynn/blob/24e4c1bce037ec88d3b8abe7059ddce7470cdada/controller/crud.go#L11-L15), since then every repository will have different function signatures.

**Comment by archSeer** [comment]
One thing I was also looking into is https://github.com/flynn/flynn/commit/e2508323722173ebc3427a303d14fea13ef3c1b8, I'd like to do away with this and only have one common way to specify the controller credentials; less things to go wrong that way.

**Comment by titanous** [comment]
I don't think the JS eventsource API allows setting headers.

**Comment by archSeer** [comment]
Ah I see, figured there had to be a good reason for that.

Another thing I'd love is a more specialised `pkg/sse` method that allows setting the other event fields (`event`, `id`), so we can simplify cases like [these](https://github.com/flynn/flynn/blob/48b1a0d379056b810c4818a4601a583da54e3073/controller/jobs.go#L307) into something that's more similar to our other streams. Maybe something in the form of `sse.Send(&sse.Event{id: '1234', event: 'name', data: someInterface})`.

Would also be lovely if we can find more generalisations on the backend, for instance a `Stream(chan in, out http.ResponseWriter)` would greatly simplify all of our streaming.
```go
func (h *Host) streamEvents(id string, w http.ResponseWriter) error {
	ch := h.state.AddListener(id)
	go func() {
		<-w.(http.CloseNotifier).CloseNotify()
		h.state.RemoveListener(id, ch)
	}()
	enc := json.NewEncoder(sse.NewWriter(w))
	w.Header().Set("Content-Type", "text/event-stream; charset=utf-8")
	w.WriteHeader(200)
	w.(http.Flusher).Flush()
	for data := range ch {
		if err := enc.Encode(data); err != nil {
			return err
		}
		w.(http.Flusher).Flush()
	}
	return nil
}
```

```go
func (h *Host) streamEvents(id string, w http.ResponseWriter) error {
	ch := h.state.AddListener(id)
	defer h.state.RemoveListener(id, ch)
	return Stream(ch, w) // blocks until CloseNotify, we might need a cleanup func() parameter as well
}
```

**Comment by titanous** [comment]
Related: #755

**Comment by archSeer** [comment]
After #748 or #749, we started emitting a whole lot of `http: multiple response.WriteHeader calls`. That should be taken care of.

One example: https://gist.github.com/anonymous/9b8d635db79b795dbe2a#file-controller-web-25fccb789418400b8e8f9f91a3d7be6f-log-L156

**Comment by titanous** [comment]
I'm closing, as list pagination has it's own issue.
